### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers.modeling_outputs'

### ISSUE THREAD

**Issue by harkiratbehl** [INK-USC/CrossFit#5]
File "/home/harkirat/research/2022/BI/crossfit_polytropon/bart.py", line 18, in <module>
    from transformers.modeling_outputs import Seq2SeqLMOutput
ModuleNotFoundError: No module named 'transformers.modeling_outputs'

Hello,

I cannot seem to run the code. I tried to check the particular commit that you specified for Transformers repo. But this path (transformers.modeling_outputs) did not exist in that commit. However, it exists in the newer commits. It seems like you might have been using some other commit.

Could the authors try to run the code and see if it works? We would really appreciate any help with this. We are really excited to use your Benchmark. 

Regards
Harkirat
https://harkiratbehl.github.io/

**Comment by cherry979988** [comment]
Hi Harkirat! Thanks for raising the issue. 

From the error message I see that you may be using the fix of `bart.py` in Issue #3 as it uses `Seq2SeqLMOutput`. That is a fix for transformer 4.10.0, as requested by the author of Issue #3.

Please use either one of the following:
* use the master branch lastest commit, and use the specified commit of transformers in README
* use the fix in #3 , and use transformer==4.10.0, torch==1.7.1

Sorry that this is a bit of a mess due to transformer upgrading and my code not being compatible. Let me know if new error messages pop up.

**Comment by harkiratbehl** [comment]
Thanks, it works with the right version of Transformer
